/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BookingForm = IDL.Record({
  'checkIn' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'message' : IDL.Text,
  'checkOut' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(BookingForm)], ['query']),
  'submitBooking' : IDL.Func([BookingForm], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BookingForm = IDL.Record({
    'checkIn' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'message' : IDL.Text,
    'checkOut' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(BookingForm)], ['query']),
    'submitBooking' : IDL.Func([BookingForm], [], []),
  });
};

export const init = ({ IDL }) => { return []; };